### ISSUE TITLE
AKS module creating AAD managed cluster

### ISSUE THREAD

**Issue by himanshumudgal08** [OT-terraform-azure-modules/terraform-azure-aks#1]
While testing your AKS module using example folder
enable_role_based_access_control & rbac_aad_managed arguments should be set as false 
otherwise that would create an issue while simply accessing AKS cluster
![image](https://user-images.githubusercontent.com/99440004/174792970-c14d7912-a4a3-427d-a00a-9ffde9f6cdfc.png)

**Comment by himanshiparnami** [comment]
By default Role Based Access Control value is true . It depends on the user requirement if the user wants to disable rbac for the cluster, can set it as false else true
